config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users do
    resource :profile
    resources :polls do
    resource :comments

  end
end

resources :links do
  member do
    put "like", to: "links#upvote"
    put "dislike", to: "links#downvote"
  end
    resources :comments
end
root "links#index"

namespace :charts do
  get "new-votes"
  get "new-users"
end

  get 'yeaornay', to: 'links#yeaornay'
  get 'choice', to: 'links#choice'
  get 'image', to: 'links#image'
  get 'scale', to: 'links#scale'
  get 'about', to: 'pages#about'
  resources :contacts, only: :create
  get 'contact-us', to: 'contacts#new', as: 'new_contact'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :plan
  has_one :profile
  has_many :links


  attr_accessor :stripe_card_token
  #If Pro users passes validations (email, password, etc.),
  #then call Stripe and tell Stripe to set up a subscription
  #upon charging customer's card.
  #Strip responds back with customer data.
  #Store customer.id as customer token and save the user.
  def save_with_subscription
    if valid?
      customer = Stripe::Customer.create(description: email, plan: plan_id, card: stripe_card_token)
      self.stripe_customer_token = customer.id
      save!
    end
  end

  has_one :profile
end

app/controllers/users/profilesDELETE_controller.rb
#class ProfilesController < ApplicationController
  # GET to /users/:user_id/profile/new
  #def new
    # Render blank profile details form
  #end
#end

app/controllers/users/profiles_controller.rb
class ProfilesController < ApplicationController
  # GET to /users/:user_id/profile/new
  def new
    # Render blank profile details form
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController#update
  #Extend default devise gem behavior so that
  #users signing up with the Pro account (plan ID 2)
  #save with a special Stripe subscription function.
  #Otherwise Devise signs up user as usual.
  # Only do this when the user is signing up


  # Extends the default Devisor behaviour so that
  # users who are signing up with the pro account is
  # saved with the special stripe function otherwise,
  # devise signs up as usual.

  def create
    super do |resource|
      if params[:plan]
        resource.plan_id = params[:plan]
        if resource.plan_id == 2
          resource.save_with_subscription
        else
          resource.save
        end
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!


  def index
    @users = User.includes(:profile)
  end

# GET to /users/:id
  def show
    @user = User.find( params[:id] )
  end


  def destroy
    @user = User.find( params[:id] )
  end
end

app/views/users/index.html.erb
<div id='community'>
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
    <h1 class="text-center">Poll Community</h1>
      <p class="text-center">Welcome to the Poll community!</p>
      <ul class="list-unstyled">
        <% @users.each do |user| %>
        <% if user.profile %>
        <li>
          <div class="well row <%= cycle('white-bg', '') %>">
            <div class="col-sm-4 text-center">

            </div>
            <div>
              <%= link_to user do %>
              <h3><%= user.profile.first_name %> <%= user.profile.last_name  %></h3>
              <p><%= user.profile.description %></p>
              <% end %>
              <p><%= user.profile.gender %></p>
              <% if user.plan_id == 2 %>
              <span class="label label-danger">PRO</span>
              <% end %>
            </div>
          </li>
        <% end %>
        <% end %>
      </ul>
    </div>
  </div>
</div>
</div>
<div class="container">
  <div class="row">
    <h2>Users</h2>
    <%= line_chart User.group_by_day(:created_at).count %>
  </div>
</div>


<!--
<div class="container">
  <div class="row">
    <div class="text-center">
      <div class="text-center col-md-4 col-md-offset-2">
      <ul>
      <%= @users.each do |user| %>

      <% end %>
    </ul>
        <br>

        <%= link_to "My Profile", user_path(current_user.id), class: 'btn btn-default btn-lg btn-block'%>
      </div>
    </div>
  </div>
</div>
-->

app/views/users/show.html.erb
<div id="content" >
  <div id="left">
    <h3 class ="text-center"><%= current_user.name  %></h3>
    <%= link_to "Create a Poll!",new_link_path(user_id: current_user.id), class: 'btn btn-default btn-sm btn-block'%>
    <%= link_to "The Poll community", users_path, class: 'btn btn-default btn-sm btn-block'%>
    <%= link_to "Edit your profile", edit_user_profile_path(user_id: current_user.id), class: 'btn btn-default btn-sm btn-block' %>
    <%= link_to "Edit your account", edit_user_registration_path, class: 'btn btn-default btn-sm btn-block'%>
    <%= link_to 'Back to Polls', links_path, class: 'btn btn-default btn-sm btn-block'%>
  </div>

  <div id="profile-mid">
  <div id="well">
    <h1 class="text-center"><h1 class ="text-center"><%= @user.profile.first_name %> <%= @user.profile.last_name %>'s Profile</h1>
        <h3>Gender: <%= @user.profile.gender %><br></h3>
        <h3>Postal Code: <%= @user.profile.zip_code %><br></h3>
        <h3>About Me:<br><%= @user.profile.description %><br></h3>
  </div>
  <h5> *Completing all the fields in your profile helps us chart and graph the user demographics
    related to the polls. Your personal identify will not be shared or displayed.
    As always, we promise to never share or sell your information!</h5>
  </br>
  </br>
  </br>
  </br>
  </br>
  </div>
</div>

<!--
<% if current_user.plan_id == 2 %> <br>
<% end %>
-->