config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users do
    resource :profile
    resources :polls do
    resource :comments

  end
end

resources :links do
  member do
    put "like", to: "links#upvote"
    put "dislike", to: "links#downvote"
  end
    resources :comments
end
root "links#index"

namespace :charts do
  get "new-votes"
  get "new-users"
end

  get 'yeaornay', to: 'links#yeaornay'
  get 'choice', to: 'links#choice'
  get 'image', to: 'links#image'
  get 'scale', to: 'links#scale'
  get 'about', to: 'pages#about'
  resources :contacts, only: :create
  get 'contact-us', to: 'contacts#new', as: 'new_contact'
end

app/models/link.rb
class Link < ApplicationRecord
  acts_as_votable
  belongs_to :user
  has_many :comments


  def self.search_by(search_term)
    where("LOWER(title) LIKE :search_term",
    search_term: "%#{search_term}")
  end
end

class Yeaornay < Link
  acts_as_votable
  belongs_to :user
  has_many :comments
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]
  before_action:authenticate_user!, except: [:index, :show]

  # GET /links
  # GET /links.json
  def index
    @links = Link.all.order('created_at DESC')
    if params[:search]
      @search_term = params[:search]
      @links= @links.search_by(@search_term)
    end
  end


  # GET /links/1
  # GET /links/1.json
  def show

  end

  # GET /links/new
  def new
    @link = current_user.links.build
  end

  def topic
  end 

  def yeaornay
    @link = current_user.links.build
  end

  def choice
    @link = current_user.links.build
  end

  def image
    @link = current_user.links.build
  end

  def scale
    @link = current_user.links.build
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links
  # POST /links.json
  def create
    @link = current_user.links.build(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
  @link = Link.find(params[:id])
  @link.upvote_by current_user
  redirect_back fallback_location: links_path
end

def downvote
  @link = Link.find(params[:id])
  @link.downvote_from current_user
  redirect_back fallback_location: links_path
end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    def authorized_user
      @link = current_user.links.find_by(id: params[:id])
      redirect_to links_path, notice: "Not authorized to edit this link" if @link.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:title, :url)
    end
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/links/_choiceform.html.erb
<%= form_for(@link) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <!DOCTYPE html>
  <html>
      <head>
          <meta name="viewport" content="width=device-width, initial-scale=1">
          <script src="https://unpkg.com/jquery"></script>
          <script src="https://surveyjs.azureedge.net/1.0.81/survey.jquery.js"></script>
          <link href="https://surveyjs.azureedge.net/1.0.81/survey.css" type="text/css" rel="stylesheet"/>
          <link rel="stylesheet" href="./index.css">

      </head>
      <body>
          <div id="surveyElement"></div>
          <div id="surveyResult"></div>

          <script type="text/javascript" src="./index.js"></script>

      </body>
  </html>

  <br>
  <div class="form-group">
    <%= f.submit "Submit", class: "btn btn-lg btn-primary" %>
  </div>

<% end %>
<script>
Survey
    .StylesManager
    .applyTheme("default");

var json = {
    "pages": [
        {
            "name": "page1",
            "title": "Who are you employed by?",
            "elements": [
                {
                    "type": "matrixdynamic",
                    "minRowCount": 1,
                    "rowCount": 1,
                    "name": "employer_names",
                    "valueName": "employers",
                    "isRequired": true,
                    "title": "Please enter all your employers",
                    "addRowText": "Add another employer",
                    "columns": [
                        {
                            "name": "name",
                            "isRequired": true,
                            "title": "Name of employer",
                            "cellType": "text"
                        }
                    ]
                }
            ]
        }, {
            "name": "page2",
            "title": "Tells us about your employer(s)",
            "elements": [
                {
                    "type": "paneldynamic",
                    "renderMode": "list",
                    "allowAddPanel": false,
                    "allowRemovePanel": false,
                    "name": "arrray_employer_info",
                    "title": "Your employers",
                    "valueName": "employers",
                    "templateTitle": "Employer name: {panel.name}",
                    "templateElements": [
                        {
                            "type": "panel",
                            "name": "panel_mployer_address",
                            "title": "Address",
                            "elements": [
                                {
                                    "type": "text",
                                    "name": "employer_address",
                                    "valueName": "address",
                                    "title": "Address"
                                }, {
                                    "type": "text",
                                    "name": "employer_phone",
                                    "valueName": "phone",
                                    "title": "Phone number:"
                                }, {
                                    "type": "text",
                                    "name": "employer_abn",
                                    "valueName": "abn",
                                    "title": "ABN"
                                }
                            ]
                        }, {
                            "type": "panel",
                            "name": "panel_employer_role",
                            "title": "What is your role?",
                            "elements": [
                                {
                                    "type": "radiogroup",
                                    "choices": [
                                        "Full time", "Part time", "Casual", "Seasonal"
                                    ],
                                    "name": "employer_role",
                                    "title": "Your role",
                                    "valueName": "role"
                                }
                            ]
                        }, {
                            "type": "panel",
                            "name": "panel_employer_hours_work",
                            "title": "What hours do you work?",
                            "elements": [
                                {
                                    "type": "text",
                                    "inputType": "number",
                                    "name": "member_hours_worked",
                                    "valueName": "hours_worked",
                                    "title": "Hours:"
                                }, {
                                    "type": "dropdown",
                                    "name": "member_hours_worked_frequency",
                                    "title": "Worked Frequency:",
                                    "valueName": "hours_worked_frequency",
                                    "startWithNewLine": false,
                                    "defaultValue": "Year",
                                    "choices": ["Day", "Week", "Fortnight", "Month", "Year"]
                                }
                            ]
                        }, {
                            "type": "panel",
                            "name": "panel_employer_income",
                            "title": "What income do you receive?",
                            "elements": [
                                {
                                    "type": "text",
                                    "inputType": "number",
                                    "name": "employer_income",
                                    "valueName": "income",
                                    "title": "Income:"
                                }, {
                                    "type": "dropdown",
                                    "name": "employer_income_frequency",
                                    "title": "Income Frequency",
                                    "valueName": "income_frequency",
                                    "startWithNewLine": false,
                                    "defaultValue": "Year",
                                    "choices": ["Day", "Week", "Fortnight", "Month", "Year"]
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ],
    "showQuestionNumbers": "off"
};

window.survey = new Survey.Model(json);

survey
    .onComplete
    .add(function (result) {
        document
            .querySelector('#surveyResult')
            .innerHTML = "result: " + JSON.stringify(result.data);
    });

$("#surveyElement").Survey({model: survey});
</script>

app/views/links/_form.html.erb
<%= form_for(@link) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>


  <div class="form-group">
    <%= f.label :topic %> <br>
    <%= f.select :url, [['None','None'],
    ['Beauty','Beauty'],
    ['Books','Books'],
    ['Computers','Computers'],
    ['Dreams','Dreams'],
    ['Education','Education'],
    ['Food','Food'],
    ['Games','Games'],
    ['Health','Health'],
    ['Money','Money'],
    ['Movies','Movies'],
    ['Music','Music'],
    ['Politics','Politics'],
    ['Relationships','Relationships'],
    ['Sports','Sports'],
    ['Shopping','Shopping'],
    ['Travel','Travel'],
    ['TV','Tv'],
    ['Work','Work'],
    ['Misc', 'Misc']] , {}, class: 'form-control' %>
  </div>

  <br>
  <div class="form-group">
    <%= f.submit "Submit", class: "btn btn-lg btn-primary" %>
  </div>

<% end %>

app/views/links/choice.html.erb
<div class ="row">
  <div class="col-md-6 col-md-offset-3">
    <div class ="well">
      <h1 class="text-center">Create a multiple choice Poll</h1>

      <%= render 'choiceform', link: @link %>

      <%= link_to 'Back', new_link_path %>
    </div>
  </div>
</div>

app/views/links/edit.html.erb
<div class ="row">
  <div class="col-md-6 col-md-offset-3">
    <div class ="well">
      <h1>Editing Poll</h1>

      <%= render 'form', link: @link %>

      <%= link_to 'Back', links_path %>
    </div>
  </div>
</div>

app/views/links/image.html.erb
<div class ="row">
  <div class="col-md-6 col-md-offset-3">
    <div class ="well">
      <h1 class="text-center">Create an Image Poll (Coming Soon!)</h1>
<!--
      <%= render 'form', link: @link %>

      <%= link_to 'Back', new_link_path %>
-->
    </div>
  </div>
</div>

app/views/links/index.html.erb
<div id="content" >
  <div id="left">
  <% if user_signed_in? %>
    <div class="text-center">
      <h3><%= current_user.name  %></h3>
    </div>
      <% if current_user.profile %>
      <%= link_to "Create a Poll", new_link_path(user_id: current_user.id), class: 'btn btn-default btn-lg btn-block' %>
      <%= link_to "View your profile", user_path(current_user.id), class: 'btn btn-default btn-lg btn-block' %>
      <%= link_to "The Poll community", users_path, class: 'btn btn-default btn-lg btn-block'%>
      <% else %>
      <%= link_to "Create your profile!", new_user_profile_path(user_id: current_user.id), class: 'btn btn-default btn-lg btn-block' %>
      <% end %>
  <% end %>
</div>

<div id="middle">
  <% @links.each do |link| %>
  <div class="links-container">
    <div class ="well ">
      <h4>Topic: <%=link.url %></h4>
      <h2><%= link_to link.title, link%></h2>

      <br>
      <div class="btn-group">
        <%= button_to like_link_path(link), :method => :put, class: "btn btn-default btn-sm" do %>
        <span class="glyphicon glyphicon-chevron-up"></span>
        Yae
        <%= link.get_upvotes.size %>
        <% end %>
        <%= button_to dislike_link_path(link), :method => :put, class: "btn btn-default btn-sm" do %>
        <span class="glyphicon glyphicon-chevron-down"></span>
        Nay
        <%= link.get_downvotes.size %>
        <% end %>
      <br>
      <h3>
        <small class="author">Submitted <%= time_ago_in_words(link.created_at)%> ago</br>by:
        <%= link.user.name %> </small>
        </h3>
        <h3 class="comments_title">
          <%= link.comments.count %> Comments
        </h3>
        <h3>
        <small class="author"><%= link_to "Poll Details", link %>
      </h3>
    </div>
</div>
<% end %>
</br>
</br>
</br>
</br>
</br>
</div>
</div>

app/views/links/new.html.erb
<div class ="row">
  <div class="col-md-6 col-md-offset-3">
    <div class ="well">
      <h1 class="text-center"> Select a survey type </h1>
      </br>
      <%= link_to "Create a Yea or Nay Poll", yeaornay_path(user_id: current_user.id), class: 'btn btn-default btn-lg btn-block' %>
      <%= link_to "Create a Multiple Choice Poll", choice_path(user_id: current_user.id), class: 'btn btn-default btn-lg btn-block' %>
      <%= link_to "Create an Image Poll", image_path(user_id: current_user.id), class: 'btn btn-default btn-lg btn-block' %>
      <%= link_to "Create a Scale Poll", scale_path(user_id: current_user.id), class: 'btn btn-default btn-lg btn-block' %>

    </div>
  </div>
</div>

app/views/links/scale.html.erb
<div class ="row">
  <div class="col-md-6 col-md-offset-3">
    <div class ="well">
      <h1 class="text-center">Create an Scale Poll (Coming Soon!)</h1>
<!--
      <%= render 'form', link: @link %>

      <%= link_to 'Back', new_link_path %>
-->
    </div>
  </div>
</div>

app/views/links/show.html.erb
<div class ="row">
  <div class="col-md-6 col-md-offset-3">
    <div class ="well">
      <h1 class="text-center">Poll Details</h1>
      <p id="notice"><%= notice %></p>

      <h1>
        <strong>Title:</strong>
        <%= @link.title %><br>
        <h3>Topic:
        <%= @link.url %><br></h3>
      </h1>
<!--
      <h3>
        <strong>Url:</strong>
        <%= @link.url %>
      </h3>
-->
      <%= button_to like_link_path(@link), :method => :put, class: "btn btn-default btn-sm" do %>
      <span class="glyphicon glyphicon-chevron-up"></span>
      Yea
      <%= @link.get_upvotes.size %>
      <% end %>

      <%= button_to dislike_link_path(@link), method: :put, class: "btn btn-default btn-sm" do %>
      <span class="glyphicon glyphicon-chevron-down"></span>
      Nay
      <%= @link.get_downvotes.size %>
      <% end %>

      <div class="text-center">
        <%= link_to 'Back to Polls', links_path, class: "btn btn-sm btn-success"  %>
        <% if @link.user == current_user %>
          <%= link_to 'Edit Your Poll', edit_link_path(@link), class: "btn btn-default" %>
          <%= link_to 'Delete Poll', @link, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
        <% end %>
      </div>



      </br>
      </br>

      <h3 class="comments_title">
        <%= @link.comments.count %> Comments
      </h3>
      <%= simple_form_for [@link, Comment.new]  do |f| %>
        <div class="field">
          <%= f.text_area :body, class: "form-control" %>
        </div>
        <br>
        <%= f.submit "Add Comment", class: "btn btn-primary" %>
      <% end %>

      <!--
      <%= link_to 'Edit', edit_link_path(@link) %> |
      -->


<div id='details'>
<div class='well'>
      <%= render :partial => @link.comments.order('created_at DESC') %>
    </div>

 </div>
 <h2>Vote Data</h2>


 <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">

      // Load the Visualization API and the corechart package.
      google.charts.load('current', {'packages':['corechart']});

      // Set a callback to run when the Google Visualization API is loaded.
      google.charts.setOnLoadCallback(drawChart);

      // Callback that creates and populates a data table,
      // instantiates the pie chart, passes in the data and
      // draws it.
      function drawChart() {

        // Create the data table.
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Yea Votes');
        data.addColumn('number', 'Nay Votes');
        data.addRows([
          ['Yea', <%= @link.get_upvotes.size %>],
          ['Nay', <%= @link.get_downvotes.size %>],

        ]);

        // Set chart options
        var options = {'title':'<%= @link.title %>',
                       'width':550,
                       'height':400};

        // Instantiate and draw our chart, passing in some options.
        var chart = new google.visualization.PieChart(document.getElementById('chart_div'));
        chart.draw(data, options);
      }
    </script>
  </head>

  <body>
    <!--Div that will hold the pie chart-->
    <div id="chart_div"></div>
</div>
</div>
</div>
</div>

app/views/links/yeaornay.html.erb
<div class ="row">
  <div class="col-md-6 col-md-offset-3">
    <div class ="well">
      <h1 class="text-center">Create a Yea or Nay Poll</h1>

      <%= render 'form', link: @link %>

      <%= link_to 'Back', links_path %>
    </div>
  </div>
</div>