config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users do
    resource :profile
    resources :polls do
    resource :comments

  end
end

resources :links do
  member do
    put "like", to: "links#upvote"
    put "dislike", to: "links#downvote"
  end
    resources :comments
end
root "links#index"

namespace :charts do
  get "new-votes"
  get "new-users"
end

  get 'yeaornay', to: 'links#yeaornay'
  get 'choice', to: 'links#choice'
  get 'image', to: 'links#image'
  get 'scale', to: 'links#scale'
  get 'about', to: 'pages#about'
  resources :contacts, only: :create
  get 'contact-us', to: 'contacts#new', as: 'new_contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :link
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :name, presence: true
  validates :email, presence: true
  validates :comments, presence: true
end

app/models/install.rb
class Install < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/link.rb
class Link < ApplicationRecord
  acts_as_votable
  belongs_to :user
  has_many :comments


  def self.search_by(search_term)
    where("LOWER(title) LIKE :search_term",
    search_term: "%#{search_term}")
  end
end

class Yeaornay < Link
  acts_as_votable
  belongs_to :user
  has_many :comments
end

app/models/plan.rb
class Plan <ActiveRecord::Base
  has_many :user
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
 validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end


#has_attached_file :avatar,
#                  :styles => { :medium => "300x300>", :thumb => "100x100>" },
#                  :default_url => "/images/style/missing.png"
#validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :plan
  has_one :profile
  has_many :links


  attr_accessor :stripe_card_token
  #If Pro users passes validations (email, password, etc.),
  #then call Stripe and tell Stripe to set up a subscription
  #upon charging customer's card.
  #Strip responds back with customer data.
  #Store customer.id as customer token and save the user.
  def save_with_subscription
    if valid?
      customer = Stripe::Customer.create(description: email, plan: plan_id, card: stripe_card_token)
      self.stripe_customer_token = customer.id
      save!
    end
  end

  has_one :profile
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  def new_votes
    render json: ActsAsVotable::Vote.all.group_by_day(:created_at).count
  end

    def new_users
      render json: User.group_by_month(:created_at).count
    end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]
  before_action:authenticate_user!, except: [:index, :show]

  # GET /links
  # GET /links.json
  def index
    @links = Link.all.order('created_at DESC')
    if params[:search]
      @search_term = params[:search]
      @links= @links.search_by(@search_term)
    end
  end


  # GET /links/1
  # GET /links/1.json
  def show

  end

  # GET /links/new
  def new
    @link = current_user.links.build
  end

  def topic
  end 

  def yeaornay
    @link = current_user.links.build
  end

  def choice
    @link = current_user.links.build
  end

  def image
    @link = current_user.links.build
  end

  def scale
    @link = current_user.links.build
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links
  # POST /links.json
  def create
    @link = current_user.links.build(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
  @link = Link.find(params[:id])
  @link.upvote_by current_user
  redirect_back fallback_location: links_path
end

def downvote
  @link = Link.find(params[:id])
  @link.downvote_from current_user
  redirect_back fallback_location: links_path
end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    def authorized_user
      @link = current_user.links.find_by(id: params[:id])
      redirect_to links_path, notice: "Not authorized to edit this link" if @link.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:title, :url)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @basic_plan = Plan.find(1)
    @pro_plan = Plan.find(2)
  end

  def new

  end



  def about
  end

end

app/controllers/polls_controller.rb
class PollsController < ApplicationController

  def index
  end

  def new
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!


  def index
    @users = User.includes(:profile)
  end

# GET to /users/:id
  def show
    @user = User.find( params[:id] )
  end


  def destroy
    @user = User.find( params[:id] )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<html>
  <head>
    <title>Poll</title>
    <%= csrf_meta_tags %>
    <link href="//fonts.googleapis.com/css?family=Open+Sans:400,700,800" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://js.stripe.com/v2/", type: 'text/javascrip' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>

  </head>

  <body>
    <nav class="navbar navbar-default navbar-static-top" role="navigation">
      <div class='container'>
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to image_tag('Poll2.png'), root_path, class: "navbar-left", size: "20"%>
        </div>

        <!--
        <div class="topnav input[type=text]">
        <input type="text" placeholder="Search">
        -->

<!-- Search bar -->
<div class="topnav input[type=text]">
  <%= form_for "",url: links_path, role: "search", method: :get do %>
  <%= text_field_tag :search, @search_term,placeholder: "Search..." %>
  <% end %>
</div>

        <div class="collapse navbar-collapse" id="main-nav-collapse">
          <div class="nav navbar-nav navbar-right">
            <div class="nav navbar-nav navbar-right">
              <% if user_signed_in? %>
              <!-- might need to change method to ":delete" for Heroku logout?-->
              <li><%= link_to "Log Out", destroy_user_session_path, :method => :get %></li>
              <% else %>
              <li><%= link_to "Log In", new_user_session_path %></li>
              <li><%= link_to "Create a Free Account", new_user_registration_path(plan: 1) %> </li>
              <%end%>
            </div>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to "Polls",links_path %></li>
              <%if current_user.profile %>
              <li><%= link_to "My Profile", user_path(current_user.id) %></li>
              <% else %>
              <li><%= link_to "Create your profile", new_user_profile_path(user_id: current_user.id)  %></li>
            <% end %>
            <% end %>
            <li><%= link_to "About Poll", about_path%></li>
            </div>
          </ul>
          <!--
          <%= form_tag("#", method: 'get', class: 'navbar-form navbar-right') do %>
  <%= search_field_tag 'search poll', nil, class: 'form-control', placeholder: 'Search Polls'  %>
  <%= submit_tag "Search", class: 'btn btn-default', :name => nil %>
<% end %>
-->
        </div><!-- /.navbar-collapse -->
      </div>
    </nav>

      <div class="container">
        <div class ="text-center">
        <% flash.each do |type, msg| %>
          <%= content_tag :div, msg, class: "alert alert-#{type}" %>
        <% end %>
      </div>
    </div>

  <%= yield %>
</br>
</br>
</br>
</br>
</br>
</br>
</body>

app/views/pages/about.html.erb
<div class="container">
  <div class="col-md-10 col-md-offset-1">
    <div class="text-center">
      <h1>Poll everyone, everywhere about everything!</h1>
      <p>
      Our mission is backed with honesty and integrity. We allow
      our guests to create polls for any topic of their choosing. Other registered guests
      can then vote on the topic with their opinion. Topics will trend upwards
      and the world will have a wholistic idea of how the mass population feels
      about a topic. Poll will then take that data and provide in depth
      charts and graphs on the demographic of all the votes. Our goal is to provide a
      visual of this data to paint a picture of where opinions derive from.
      </p>
    </div>
  </div>
</div>
</br>
</br>
</br>
</br>

<h4 class=text-center >
  <%= link_to "Contact Us", new_contact_path %>
</h4>

app/views/pages/home.html.erb
<div class= "container center-text">
  <div class= "text-center">
  <h1>Welcome to Poll! </h1>
  <h3>A site that gathers opinions.</h3>
</div>
<div class="container home-signup-links">

<% if user_signed_in? %>
  <div class="col-md-6">
    <div class="well">
      <h2 class="text-center"> Your Profile</h2>
      <%if current_user.profile %>
      <%= link_to "Edit your profile", edit_user_profile_path(user_id: current_user.id), class: 'btn btn-default btn-lg btn-block' %>
      <%= link_to "View your profile", user_path(current_user.id), class: 'btn btn-default btn-lg btn-block' %>
      <% else %>
      <%= link_to "Create your profile!", new_user_profile_path(user_id: current_user.id), class: 'btn btn-default btn-lg btn-block' %>

      <% end %>
    </div>
  </div>
      <div class="col-md-6">
        <div class="well">
          <h2 class="text-center">The Community</h2>
          <p>Visit the community to see all public polls!</p>
          <%= link_to "Visit the community", users_path, class: 'btn btn-default btn-lg btn-block'%>

    </div>
  </div>
  <% else %>
    <!-- Basic Membership -->
    <div class="col-md-6">
      <div class="well">
        <h2 class="text-center">Basic Membership</h2>
        <h4 class="text-center">Sign up for free and get basic access to the community.</h4>
        <br>

        <!-- Using Query string parameters, we can pass info via URL -->
        <%= link_to "Sign up with Basic", new_user_registration_path(plan: @basic_plan.id), class: 'btn btn-primary btn-lg btn-block' %>
      </div>
    </div>

    <!-- Pro Membership -->
    <div class="col-md-6">
      <div class="well">
        <h2 class="text-center">Pro Membership</h2>
        <h4 class="text-center">Get access to the community and contact info for only $10/month!</h4>
        <br>
        <%= link_to "Sign up with Pro", new_user_registration_path(plan: @pro_plan.id), class: 'btn btn-success btn-lg btn-block' %>
      </div>
    </div>

  <% end %>
</div>